services:
  db:
    container_name: simple-auth-db
    image: couchbase:latest
    ports: 
      - 8091-8097:8091-8097
      - 9123:9123
      - 11207:11207
      - 11210:11210
      - 11280:11280
      - 18091-18097:18091-18097
    networks:
      - simpleauth_network
  
  api:
    container_name: simple-auth-api
    image: simple-auth-api
    build: .
    ports:
      - 8080:8080
    networks:
      - simpleauth_network

networks:
  simpleauth_network: